FROM python:3.12-slim
WORKDIR /app
COPY sync-requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY index_meilisearch.py .
CMD ["python3", "index_meilisearch.py", "--delta"]
